name: qnotes_advanced
description: A feature-rich, beautiful note-taking app with advanced functionality

# Prevent publishing to pub.dev
publish_to: 'none'

# App version
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core functionality
  intl: ^0.18.1                    # Date formatting and internationalization
  shared_preferences: ^2.2.2      # Local storage for settings
  path_provider: ^2.1.1           # File system paths
  
  # Database & Storage
  sqflite: ^2.3.0                 # SQLite database for note persistence
  
  # UI & Icons
  cupertino_icons: ^1.0.6         # iOS-style icons
  
  # Utilities
  share_plus: ^7.2.1              # Share notes functionality
  url_launcher: ^6.2.1            # Launch URLs and external apps
  
  # State Management
  provider: ^6.1.1                # State management solution

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting and code quality
  flutter_lints: ^3.0.0

# Flutter configuration
flutter:
  uses-material-design: true

  # App assets (uncomment and add your assets)
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/sounds/

  # Custom fonts (uncomment to use custom fonts)
  # fonts:
  #   - family: SF Pro Display
  #     fonts:
  #       - asset: fonts/SFProDisplay-Regular.ttf
  #       - asset: fonts/SFProDisplay-Medium.ttf
  #         weight: 500
  #       - asset: fonts/SFProDisplay-Semibold.ttf
  #         weight: 600
  #       - asset: fonts/SFProDisplay-Bold.ttf
  #         weight: 700